---
name: Build Pipeline
on:
  push:
    branches: [main]

jobs:
  dev:
    name: Deploy Dev
    uses: naveen-visions/workflows/.github/workflows/test.yaml@main
    # with:
    #  gitopsRepo: naveen-visions/testing-pipeline
    #  environment: main
    secrets: inherit
