---
name: Build Pipeline
on:
  push:
    branches: [main]
permissions:     
  contents: write     
  id-token: write

jobs:
  dev:
    name: Deploy Dev
    uses: naveen-visions/workflows/.github/workflows/revert.yml@main
    with:
    #  gitopsRepo: naveen-visions/testing-pipeline
     rollback_tag: 1.0.14
    secrets: inherit 
    
