---
name: Build Pipeline
on:
  push:
    branches: [main]

jobs:
  dev:
    name: Deploy Dev
    uses: naveen-visions/workflows/.github/workflows/testing.yml@gitops
    with:
     gitopsRepo: naveen-visions/testing-pipeline
     environment: main
    secrets: inherit
