---
name: Build Pipeline
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, edited]
permissions:     
  contents: write     
  id-token: write

jobs:
  dev:
    name: Deploy Dev
    uses: naveen-visions/workflows/.github/workflows/check.yml@check
    # with:
    # #  gitopsRepo: naveen-visions/testing-pipeline
    #  rollback_tag: 1.0.16
    secrets: inherit 
    
