---
name: Build Pipeline
on:
  push:
    branches: [main1]
permissions:     
  contents: write     
  id-token: write

jobs:
  dev:
    name: Deploy Dev
    uses: naveen-visions/workflows/.github/workflows/cache.yml@check
    secrets: inherit 

  # testing:
  #   runs-on: ubuntu-latest
  #   # needs: dev
  #   steps:
  #     # - name: testing
  #     #   run: |
  #     #     echo "this is testing ${{ needs.dev.outputs.output_test }}"
  #     - name: testing1
  #       uses: naveen-visions/workflows/.github/workflows/cache.yml@check
    
