---
name: Build Pipeline
on:
  push:
    branches: [main]

jobs:
  dev:
    name: Deploy Dev
    uses: naveen-visions/workflows/.github/workflows/revert.yaml@main
    with:
    #  gitopsRepo: naveen-visions/testing-pipeline
     rollback_tag: 1.0.12
    secrets: inherit
